### ISSUE TITLE
Fedora 31

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-base-container#196]
I'd like to update Python container with Python 3.7 to Fedora 31. What can I do to make s2i-[base,core] available with Fedora 31?

**Comment by pkubatrh** [comment]
Rebase the Fedora Dockerfile in this repository to fedora:31 and then create a PR against Fedora Pagure for both of the images (against f31 and master please), I can merge them for you.

https://src.fedoraproject.org/container/s2i-core
https://src.fedoraproject.org/container/s2i-base/

The problem is that it seems there are no f31 branches yet. :/

**Comment by frenzymadness** [comment]
Got it, I'll first check what is the status of branches.

Btw, [s2i-core has rawhide](https://src.fedoraproject.org/container/s2i-core/blob/master/f/Dockerfile.fedora#_2) in the master branch but s2i-base [has f30](https://src.fedoraproject.org/container/s2i-base/blob/master/f/Dockerfile.fedora#_2). Should we follow Fedora branching there and keep rawhide images in master branch?

**Comment by frenzymadness** [comment]
Moreover, images in this repository have F28 as a base image, which is even more confusing. I assume that https://registry.fedoraproject.org/ is based on repositories on `src.fedoraproject.org/container/` and this one server as publicly avaibalbe for users. Am I right?

**Comment by pkubatrh** [comment]
>Should we follow Fedora branching there and keep rawhide images in master branch?

Yes, that makes sense to me. I think I just forgot to add it to s2i-base master (the rawhide tag) since you first need to build s2i-core and wait for it to get to a registry before you can continue with building s2i-base :/

>I assume that https://registry.fedoraproject.org/ is based on repositories on src.fedoraproject.org/container/ and this one server as publicly available for users. Am I right?

Exactly. Content in the Fedora dist-git gets pushed to the Fedora registry, while this servers as the upstream for Fedora dist-git. Unfortunately the source sync between these two places does not happen that often and is very low priority.

**Comment by frenzymadness** [comment]
Thank you, I'll try to clean these repositories a little bit. F31 branches for s2i-[core,base] requested in https://pagure.io/releng/fedora-scm-requests/issue/19394 and https://pagure.io/releng/fedora-scm-requests/issue/19395

**Comment by frenzymadness** [comment]
Update done and now I understand the hierarchy of images better. Thank you.
