### ISSUE TITLE
Use versions for sti-base Docker image

### ISSUE THREAD

**Issue by hanzz** [sclorg/s2i-base-container#68]
Hi,

I think for the future development of sti-base, we should use some sort of versioning of Docker image.
Currently, all images using sti-base uses something like this:

```
FROM openshift/base-centos7
```

This pulls the latest version of sti-base from Docker hub, which is OK for development, but once there's some release, users should be able to rebuild the released Docker image based on sti-base and get the same image as the shipped one. This is not possible, because the originally released Docker image could be built with older base image.

This is real problem when the so called "API" of the sti-base Docker image changes (see https://github.com/openshift/sti-base/commit/6eb7fe23e178353c450b81e56f71e9ac02aa14ed for an example of such change).

After that change, all the images built with older revision stops working when rebuilt by the user. This is not good.

I think we should at least try bumping the Version label in Dockerfile on each change breaking the backward compatibility for consumer of sti-base Docker image. That way, it would be easy to find out changes breaking backward compatibility and also to base the Docker image on the right version of sti-base when built in OSBS.

So, the only thing I'm asking for is that when you merge pull request which changes backward compatibility, just bump the Version label :).

**Comment by hhorak** [comment]
+1
And I'd also like to propose to use the `Version` label for centos-based Dockerfile. Once OSBS is used in centos, it will be necessary. Until then it may be used at least for specifying the "API".

**Comment by bparees** [comment]
the image already contains a label with the commit it was built from:
 "io.openshift.builder-base-version": "71a650e",

is that not sufficient here?

**Comment by hhorak** [comment]
@bparees Well, you can't tell whether the new build requires some change in the layered images or not, so from my PoV this doesn't help here.

**Comment by mfojtik** [comment]
@hanzz how bumping the Version label helps users pair the base image with the framework image?
@hhorak how is the `Version` label different from the `io.openshift.builder-base-version` or `io.openshift.builder-version` ?

**Comment by mfojtik** [comment]
Instead of doing this I think we should get rid of all "API" kind of things from sti-base and leave it as common "dependency" only image.

**Comment by bparees** [comment]
@mfojtik pretty sure we've been there before.  

the real issue here is that sti-base was never intended to be consumed by anything other than our sti images, and our sti images are always going to be built based on the latest sti-base image.  it's not something we anticipated needing to provide "compatibility" for.

if an individual user is trying to build our sti images themselves, then they need to use the latest sti-base image (which "docker build --pull" accomplishes).  it's not different from trying to build on top of centos and not using the most current centos image.

**Comment by hanzz** [comment]
@mfojtik 
> how bumping the Version label helps users pair the base image with the framework image?

OSBS uses that in the tag - openshift3/sti-base:1.0. in SCL, we could therefore use FROM openshift3/sti-base:1.0 and be sure that the image we have released just works even when rebuilt.

I think @bparees is right here:
> the real issue here is that sti-base was never intended to be consumed by anything other than our sti images, and our sti images are always going to be built based on the latest sti-base image. it's not something we anticipated needing to provide "compatibility" for.

For you this use-case makes sense, but for software collections it's not so clear. We do a release and then do not touch the released version. Once we do another release, we want to use new sti-base image even if it introduces the backward incompatibilities, but since we do not update all the software collections, but just some of them, we still want to have the older collections to work and be rebuild-able by the user.

Therefore we may want to use older sti-base for older software collections (which are not updated by particular update) and new sti-base for newer software collections (which for example are updated in rhscl-2.1).

So we would like to somehow find out that there have been incompatible changes done by the sti-base uptream, so we should bump the version when updating our sti-base Docker image.

**Comment by hanzz** [comment]
@bparees wrote:
> if an individual user is trying to build our sti images themselves, then they need to use the latest sti-base image (which "docker build --pull" accomplishes). it's not different from trying to build on top of centos and not using the most current centos image.

I think the difference here is that centos provides some sort of backward compatibility. Their Dockerfile does not change a lot in the past. And the system itself is not expected to break after its updated because of changes in default paths. It is more stable environment than sti-base. This is of course expected and OK.

I think it would be useful also for you to allow Openshift users to create their images based on sti-base. You certainly don't want them to follow docker pushes closely all the time to be sure new update of sti-base does not break their image. It would be good for them to use the stable version if they want and update to new version which breaks the compatibility when they really want it.

**Comment by mfojtik** [comment]
@hanzz `docker build --pull` ?

**Comment by mfojtik** [comment]
@hanzz what you are really suggesting is that we tag the upstream images in Dockerhub?

**Comment by hanzz** [comment]
@mfojtik Yes, I think that would make sense. I mainly care about builds in OSBS (therefore I want the Version label to be bumped when backward incompatibility is introduced), but having tags also in Dockerhub would be nice. I think these are two separate things. At first, there have be some decision whether commits breaking the backward compatibility from the sti-base consumer's view should result in Version bump. Then we can think about using that as a tag in Dockerhub.

**Comment by hanzz** [comment]
@mfojtik wrote:
> @hanzz docker build --pull ?

I'm not sure I understand what you want to say by that, sorry. The problem is that for already released images, we want to use specific version of sti-base (because the images do not have to work with the sti-base:latest).

**Comment by mfojtik** [comment]
@hanzz I agree, `:latest` is not a version.

@bparees what do you think? I like the idea of having "real" tags for our images, so we can stick to some "released" versions (at least for RHEL7) so we can 'freeze' base image for already released images for features (that does not prevent us from upgrading packages/security fixes, which can be minor version bump).

**Comment by bparees** [comment]
> @bparees what do you think? 

i don't completely hate it :)

we could always just push (for centos) w/ the commit id we built from.

for rhel it's trickier since that comes out of internal build processes we don't control.  and we don't publish sti-base.

**Comment by jawnsy** [comment]
@bparees Apologies if my ignorance of the mechanics of this are showing, but:

> for rhel it's trickier since that comes out of internal build processes we don't control. and we don't publish sti-base.

Can't we publish the RHEL-based variant of sti-base to `registry.access.redhat.com`, similarly for all the [Red Hat-supported builder images](https://access.redhat.com/containers/?filters=category_builder)? Or was your statement referring only to Docker Hub images?  I'm replying to an old comment, so it's also possible something has changed in the 8 months since you wrote it :smile:

**Comment by bparees** [comment]
> Can't we publish the RHEL-based variant of sti-base to registry.access.redhat.com, similarly for all the Red Hat-supported builder images? 

we could have, but there were a lot of reasons we didn't want to do that which i'm not going to rehash here since at this point the old base image is deprecated and the SCL team is publishing their own s2i-base image (both rhel and centos versions) which is now the base for all current relevant images, so it's moot.

**Comment by hhorak** [comment]
We have the version=X field as label, which also is usually used as a tag, so images should be able to pick particular version.. On the other hand, we should avoid doing incompatible changes if possible, because we don't control all the images based on this image, no matter what we wish.. Anyway, there were no incompatible changes for quite long time, so let's cross this river once we get there.. and close it for now.
